### ISSUE TITLE
Static modification causes ``zend_mm_heap corrupted``

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/pthreads#104] opened 2023-03-12 15:02 UTC
Environment
==========

  * PHP: 8.0.19
  * pthreads: 4.0.0
  * OS: Windows x64

Summary
======

After much research, I found the source of a problem that happens to me by reproducing it at will. 

It seems that there is a strange behavior with the modification of a static variable, through a callable in another thread than the one that created this callable.

The example code will speak better than my explanations which can be shaky

Reproducing Code
==============

A class :
```php
class AsyncEvilTask extends AsyncTask {
	private $onRun;
	private $onCompletion;

	public function __construct(callable $onRun, callable $onCompletion) {
		$this->onRun = $onRun;
		$this->onCompletion = $onCompletion;
	}

	public function onRun() : void {
		$callable = $this->onRun;
		$callable($this);
	}

	public function onCompletion(): void {
		$callable = $this->onCompletion;
		$callable($this);
	}
}
```
In a PocketMine-MP plugin class:
```php
class Main extends PluginBase {
     public static $test = [
		"Angel"
     ];

    public function onEnable(): void{
		$this->getServer()->getAsyncPool()->submitTask(new AsyncEvilTask(
			function() {
				self::$test[0] = "Evil";
			}, function() {
				var_dump(self::$test);
			}
		));
    }
}
```

Expected Output
=============

A var_dump of an array containing an element: a string equal to Angel.

Actual Output
============

``zend_mm_heap corrupted`` error with no more explanation

**Comment by dktapps** [comment] 2023-03-12 15:23
This is caused by the same issue reported here: https://github.com/pmmp/pthreads/issues/59

This issue was fixed in 5.1.4.

**Closed as completed by dktapps** 2023-03-12 15:23 UTC
